# Install opencv library

In [1]:
pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy

In [3]:
numpy.__version__

'1.26.1'

In [4]:
import cv2

# Check the version

In [5]:
pip install --upgrade opencv-python

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
cv2.__version__

'4.10.0'

# Reading Image

In [7]:
import cv2

In [8]:
import numpy as np

In [9]:
img=cv2.imread('leo.jpg')

In [10]:
print(img)

[[[ 27  27  27]
  [ 27  27  27]
  [ 27  27  27]
  ...
  [ 12  10  10]
  [ 12  10  10]
  [ 12  10  10]]

 [[ 27  27  27]
  [ 27  27  27]
  [ 27  27  27]
  ...
  [ 12  10  10]
  [ 12  10  10]
  [ 12  10  10]]

 [[ 27  27  27]
  [ 27  27  27]
  [ 27  27  27]
  ...
  [ 12  10  10]
  [ 12  10  10]
  [ 12  10  10]]

 ...

 [[119 117 129]
  [119 117 129]
  [118 116 128]
  ...
  [171 173 174]
  [171 173 174]
  [172 174 175]]

 [[119 116 131]
  [118 115 130]
  [118 115 130]
  ...
  [171 173 174]
  [171 173 174]
  [172 174 175]]

 [[118 115 130]
  [118 115 130]
  [118 115 130]
  ...
  [171 173 174]
  [171 173 174]
  [172 174 175]]]


# Display an Image

In [23]:
cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

# Greyscale

In [40]:
grey = cv2.imread('leo.jpg',0)

In [41]:
grey

array([[ 27,  27,  27, ...,  10,  10,  10],
       [ 27,  27,  27, ...,  10,  10,  10],
       [ 27,  27,  27, ...,  10,  10,  10],
       ...,
       [121, 121, 120, ..., 173, 173, 174],
       [121, 120, 120, ..., 173, 173, 174],
       [120, 120, 120, ..., 173, 173, 174]], dtype=uint8)

# Greyscale image Display

In [42]:
cv2.imshow("greyimage",grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Write an image

In [32]:
cv2.imwrite('saveimage.jpg',img)

True

In [3]:
pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import cv2
import numpy as np

In [6]:
view = cv2VedioCapture("C:\Users\aedpu\Documents\VIKNESHRAJ D V\An extended look at the 2014 Royal Rumble commercial.mp4")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1777293458.py, line 1)

In [ ]:
while